
select * from ingredientes;
select * from clientes;
select * from comandas;
select * from ingredientes_platos;
select * from platos;

--1 
select * from ingredientes;
select ID,upper(nombre) "NOMBRE",CATEGORIA, ESTADO from ingredientes where estado = 'SOLIDO';

--2 REVISAR
SELECT * FROM COMANDAS;
SELECT COUNT (*) SYSDATE ;

--3
SELECT NOMBRE FROM INGREDIENTES WHERE LENGTH(NOMBRE) >= 27 ;

--4  REVISAR
SELECT * FROM PLATOS;
SELECT COUNT(NOMBRE) "PLATOS" FROM PLATOS WHERE TIEMPO_PREPARACION = 10;
SELECT COUNT(NOMBRE) "PLATOS" FROM PLATOS WHERE TIEMPO_PREPARACION = 15;
SELECT COUNT(NOMBRE) "PLATOS" FROM PLATOS WHERE TIEMPO_PREPARACION = 25;

--5
select * from platos;
SELECT ROUND(AVG(PRECIO),2)"PRECIO" FROM PLATOS;

--6
select * from clientes;
SELECT UPPER(TRIM(NOMBRE))"NOMBRE",LOCALIDAD FROM CLIENTES;

--7
SELECT NOMBRE "PLATO MÁS CARO", PRECIO FROM PLATOS WHERE PRECIO = (SELECT MAX(PRECIO) FROM PLATOS);

--8
select * from ingredientes_platos;
select * from platos;
SELECT INGREDIENTES_PLATOS.CANTIDAD,ingredientes_platos.id_ingrediente FROM PLATOS JOIN INGREDIENTES_PLATOS ON platos.id = ingredientes_platos.id_ingrediente WHERE ID_PLATO = 3 ;
SELECT  INGREDIENTES.NOMBRE FROM INGREDIENTES JOIN PLATOS ON INGREDIENTES.INGREDIENTES_ID = PLATOS.ID WHERE ID_PLATO = 3;

--9

--10
SELECT COUNT(NOMBRE)"INGR LACTEOS" FROM INGREDIENTES WHERE CATEGORIA = 'LACTEO';

--11
SELECT NOMBRE,CATEGORIA FROM INGREDIENTES WHERE NOMBRE LIKE 'Pi%';

--12
select * from comandas;
SELECT ID_PLATO FROM COMANDAS WHERE ID_PLATO = 5 AND ESTADO = 'COBRADO' ;

--13
SELECT NOMBRE FROM PLATOS (SELECT NOMBRE FROM INGREDIENTES WHERE NOMBRE = 'Aceite de oliva virgen extra');

--14


--15
SELECT * FROM COMANDAS;
SELECT * FROM PLATOS;
SELECT ID_PLATO FROM COMANDAS WHERE FECHA ='01032021' AND HORA = '21:16';

SELECT NOMBRE,PLATOS.ID_PLATO FROM PLATOS JOIN COMANDAS ON PLATOS.ID = COMANDAS.ID_PLATO WHERE FECHA ='01032021' AND HORA = '21:16';

--16
SELECT COUNT(ID_PLATO)"NOMBRE" FROM COMANDAS WHERE ID_PLATO = 4 ;

--17

--19
SELECT NOMBRE FROM CLIENTES JOIN COMANDAS ON ;

--31
SELECT DISTINCT CATEGORIA FROM INGREDIENTES ;









