--1 BIEN
SELECT * FROM COMANDAS;
SELECT HORA FROM COMANDAS WHERE MESA = 2;

--2 REVISAR
SELECT * FROM CLIENTES;
SELECT * FROM COMANDAS;
SELECT DISTINCT CLIENTES.LOCALIDAD FROM CLIENTES JOIN COMANDAS ON CLIENTES.ID = COMANDAS.ID_CLIENTE;

--3 BIEN
SELECT * FROM CLIENTES;
SELECT DISTINCT CLIENTES.TELEFONO FROM CLIENTES JOIN COMANDAS ON CLIENTES.ID = COMANDAS.ID_CLIENTE WHERE HORA = '21:27';

--4 REVISAR
select * from ingredientes;
SELECT NOMBRE FROM INGREDIENTES ;

--5 REVISAR
SELECT SUBSTR(NOMBRE,5,7) FROM INGREDIENTES;

--6 BIEN
SELECT COUNT(*) FROM INGREDIENTES WHERE LENGTH(NOMBRE) > 10;

--7 
SELECT * FROM PLATOS;
SELECT LOWER(NOMBRE)"NOMBRE" FROM PLATOS WHERE NOMBRE IN ('%p','%r','%a','%s','%t') AND PRECIO < 10 AND tiempo_preparacion > 7;-- intente este pero no me sale 
SELECT LOWER(NOMBRE)"NOMBRE" FROM PLATOS WHERE NOMBRE not like '%e' AND PRECIO < 10 AND tiempo_preparacion > 7; -- este lo intente pero no se me quita el que empieca la e

--8 BIEN
SELECT * FROM PLATOS;
SELECT *FROM COMANDAS;
SELECT PLATOS.PRECIO FROM PLATOS JOIN COMANDAS ON PLATOS.ID = COMANDAS.ID_PLATO WHERE FECHA ='010321' AND HORA = '21:10';

--9 BIEN
SELECT * FROM INGREDIENTES;
SELECT UPPER(NOMBRE) FROM INGREDIENTES WHERE ESTADO = 'LIQUIDO';
SELECT UPPER(REPLACE(NOMBRE,' ')) FROM INGREDIENTES WHERE ESTADO = 'LIQUIDO';

--10 REVISAR TENGO QUE UTILIZAR MÁS DE UN JOIN  COMANDAS.ID_PLATO, COMANDAS.ID_CLIENTE Y 
SELECT * FROM CLIENTES,PLATOS,COMANDAS;
SELECT CLIENTES.NOMBRE,PLATOS.NOMBRE FROM CLIENTES JOIN PLATOS ON ;

--11 BIEN
SELECT * FROM COMANDAS,PLATOS;
SELECT TRUNC(SUM(PLATOS.PRECIO),0) FROM PLATOS JOIN COMANDAS ON PLATOS.ID = COMANDAS.ID_PLATO;

--12 BIEN
SELECT * FROM INGREDIENTES;
SELECT  'El ingrediente con más letras es '|| nombre "NOMBRE",LENGTH(NOMBRE) "LETRAS" FROM INGREDIENTES WHERE NOMBRE = (SELECT MAX(NOMBRE) FROM INGREDIENTES);

--13 BIEN HE PUESTO EL DISTINCT PARA QUE NO SE REPITAN LOS PLATOS
SELECT * FROM INGREDIENTES_PLATOS;
SELECT * FROM PLATOS;
SELECT * FROM ingredientes;

SELECT  DISTINCT PLATOS.NOMBRE FROM INGREDIENTES 
    JOIN INGREDIENTES_PLATOS ON INGREDIENTES.ID = INGREDIENTES_PLATOS.ID_INGREDIENTE
    JOIN PLATOS ON INGREDIENTES_PLATOS.ID_PLATO = PLATOS.ID 
    WHERE INGREDIENTES.CATEGORIA = 'VERDURA';

SELECT PLATOS.NOMBRE FROM PLATOS JOIN INGREDIENTES ON PLATOS.ID = INGREDIENTES.ID WHERE INGREDIENTES.CATEGORIA = 'VERDURA';

--14 BIEN
SELECT  UPPER(CLIENTES.NOMBRE)"NOMBRE" FROM CLIENTES JOIN COMANDAS ON CLIENTES.ID = COMANDAS.ID_CLIENTE WHERE FECHA = '010321' AND HORA BETWEEN '21:20' AND '21:40' AND ESTADO = 'COCINA';

--15 BIEN
SELECT * FROM PLATOS;
SELECT INITCAP(NOMBRE)"NOMBRE" FROM PLATOS WHERE PRECIO BETWEEN 5 AND 8;

--16 BIEN
SELECT DISTINCT INGREDIENTES.CATEGORIA FROM INGREDIENTES 
    JOIN INGREDIENTES_PLATOS ON INGREDIENTES.ID = INGREDIENTES_PLATOS.ID_INGREDIENTE
    JOIN PLATOS ON INGREDIENTES_PLATOS.ID_PLATO = PLATOS.ID 
    WHERE PLATOS.ID = 2;
    
--17 REVISAR
SELECT * FROM COMANDAS;
SELECT LOWER(ESTADO) FROM COMANDAS ORDER BY ESTADO DESC;-- FALTA QUE NO SE REPITA
SELECT DISTINCT(ESTADO) FROM COMANDAS ORDER BY ESTADO DESC;-- ME FALTA PONERLO EN MINUS
SELECT DISTINCT(LOWER(ESTADO)) FROM COMANDAS ORDER BY ESTADO DESC;--NO

--18
SELECT NOMBRE FROM INGREDIENTES WHERE NOMBRE IN ('G%','P%'); -- NO ME SALE, ME FALTA ALGO
SELECT NOMBRE FROM INGREDIENTES WHERE NOMBRE LIKE 'P%';

--19
SELECT COUNT (*) FROM INGREDIENTES WHERE CATEGORIA = 'VERDURA' AND NOMBRE LIKE 'P%';

--20 
SELECT * FROM INGREDIENTES_PLATOS;
SELECT  platos.nombre "Plato",ingredientes_platos.cantidad "Cant" FROM INGREDIENTES 
    JOIN INGREDIENTES_PLATOS ON INGREDIENTES.ID = INGREDIENTES_PLATOS.ID_INGREDIENTE
    JOIN PLATOS ON INGREDIENTES_PLATOS.ID_PLATO = PLATOS.ID 
    WHERE INGREDIENTES.NOMBRE = 'Cebolla' AND INGREDIENTES_PLATOS.ID_INGREDIENTE = 3; 
    
--21
SELECT COUNT(*) FROM COMANDAS WHERE HORA BETWEEN '21:00' AND '21:10' AND FECHA = '010321';

--22
SELECT MAX(PLATOS.PRECIO) FROM PLATOS JOIN COMANDAS ON PLATOS.ID = COMANDAS.ID_PLATO WHERE ESTADO = 'SERVIDO' AND FECHA = '010321';

--23


--24
SELECT ROUND(AVG(CANTIDAD),3) FROM INGREDIENTES_PLATOS;

--25
SELECT PLATOS.NOMBRE FROM PLATOS JOIN COMANDAS ON PLATOS.ID = COMANDAS.ID_PLATO WHERE COMANDAS.ESTADO = 'SERVIDO' AND FECHA = '010321' AND HORA = '21:25';

--26
SELECT TIEMPO_PREPARACION FROM PLATOS WHERE PRECIO = (SELECT MIN(PRECIO) FROM PLATOS);

--27
SELECT NOMBRE, LOCALIDAD FROM CLIENTES WHERE NOMBRE LIKE '%n';

--28
SELECT ;

--29
SELECT * FROM PLATOS;
SELECT * FROM INGREDIENTES_PLATOS;

SELECT  INGREDIENTES.nombre FROM INGREDIENTES 
    JOIN INGREDIENTES_PLATOS ON INGREDIENTES.ID = INGREDIENTES_PLATOS.ID_INGREDIENTE
    JOIN PLATOS ON INGREDIENTES_PLATOS.ID_PLATO = PLATOS.ID 
    WHERE PLATOS.ID = 3 ; --ME FALTA LA CANTIDAD

--30 
SELECT COUNT(*)  FROM CLIENTES JOIN COMANDAS ON CLIENTES.ID = COMANDAS.ID_CLIENTE WHERE NOMBRE = 'Jose Miguel';

--31
SELECT NOMBRE FROM INGREDIENTES WHERE CATEGORIA = 'CONDIMENTO';
